

# bitcoin

export BITCOIN_LOCAL_DIR="/work/locallnd/.bitcoin"

alias bitcoin-local-cli="docker exec -it giggossip_bitcoin /work/bitcoin/src/bitcoin-cli -datadir=$BITCOIN_LOCAL_DIR"



# lightning network

export LND_DIR="/work/locallnd/.lnd"

alias lnd1="docker exec -it giggossip_lightning_node_1 /work/lnd/lnd-debug --lnddir=$LND_DIR"
alias lnd2="docker exec -it giggossip_lightning_node_2 /work/lnd/lnd-debug --lnddir=$LND_DIR"
alias lnd3="docker exec -it giggossip_lightning_node_3 /work/lnd/lnd-debug --lnddir=$LND_DIR"

alias lncli1="docker exec -it giggossip_lightning_node_1 /work/lnd/lncli-debug -n regtest --lnddir=$LND_DIR --rpcserver=localhost:10009"
alias lncli2="docker exec -it giggossip_lightning_node_2 /work/lnd/lncli-debug -n regtest --lnddir=$LND_DIR --rpcserver=localhost:11009"
alias lncli3="docker exec -it giggossip_lightning_node_3 /work/lnd/lncli-debug -n regtest --lnddir=$LND_DIR --rpcserver=localhost:11010"



# gig-gossip

export GIG_GOSSIP_DIR="/work/locallnd/.giggossip"

alias btc-test="docker run -it -v ./work/locallnd/.giggossip:/work/locallnd/.giggossip --network=giggossip awazcognitum/gig-gossip-base:0.1 dotnet /work/gig-gossip/net/NGigGossip4Nostr/BTCTest/bin/Debug/net7.0/BTCTest.dll --basedir=$GIG_GOSSIP_DIR"

