version: "3"

services:

  bitcoin:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_bitcoin
    restart: on-failure
    command: ["/work/bitcoin/src/bitcoind","-datadir=/work/locallnd/.bitcoin","-printtoconsole"]
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./work/locallnd/.bitcoin:/work/locallnd/.bitcoin:Z
      # - ./work/locallnd/.giggossip:/work/locallnd/.giggossip:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  lightning_node:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9735:9735
      - 10009:10009
      - 8080:8080
    volumes:
      - ./work/locallnd/.lnd:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    logging:
      driver: local
      options:
        max-size: "100m"




  nostr:
    image: python:3.9.17-slim-bookworm

    container_name: giggossip_nostr
    restart: on-failure
    working_dir: /work/locallnd/.nostr_relay
    command: sh -c "pip install nostr-relay && pip install SQLAlchemy==2.0.27 && nostr-relay -c config.yaml serve"
    ports:
      - 6969:6969
    volumes:
      - ./work/locallnd/.nostr_relay:/work/locallnd/.nostr_relay:Z
    logging:
      driver: local
      options:
        max-size: "100m"




  logger_api:
    image: awazcognitum/logger_api:latest

    container_name: logger_api
    restart: on-failure
    ports:
      - 7187:80
    volumes:
      - ./work/locallnd/:/app/data/:Z
    environment:
      - ServiceUri=https://regtest.fairide.io/logger/
    logging:
      driver: local
      options:
        max-size: "100m"


  wallet_api:
    image: awazcognitum/giggossip-backend:latest

    container_name: wallet_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net8.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7101:7101
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  settler_api:
    image: awazcognitum/giggossip-backend:latest

    container_name: settler_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigGossipSettlerAPI/bin/Debug/net8.0/GigGossipSettlerAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7189:7189
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    logging:
      driver: local
      options:
        max-size: "100m"



  proxy:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - URL=testnet.fairide.io
      - VALIDATION=http
      - SUBDOMAINS=
      - EMAIL=a.waz@cognitum.eu
    volumes:
      - ./work/locallnd/proxy/swag_config/config:/config
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped


networks:
  default:
    name: giggossip
    driver: bridge
