version: "3"

services:

  bitcoin:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_bitcoin
    restart: on-failure
    # command: ["sleep","infinity"]
    command: ["/work/bitcoin/src/bitcoind","-datadir=/work/locallnd/.bitcoin","-printtoconsole","-debug"]
    # command: bash -c "
    #     /work/bitcoin/src/bitcoind -datadir=/work/locallnd/.bitcoin
    #     && sleep infinity"
    ports:
      - 18332:18332
      - 28332:28332
      - 28333:28333
    volumes:
      - ./work/locallnd/.bitcoin:/work/locallnd/.bitcoin:Z
      # - ./work/locallnd/.giggossip:/work/locallnd/.giggossip:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  lightning_node_1:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_1
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9735:9735
      - 10009:10009
      - 8080:8080
    volumes:
      - ./work/locallnd/.lnd:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    logging:
      driver: local
      options:
        max-size: "100m"



  lightning_node_2:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_2
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9734:9734
      - 11009:11009
      - 8180:8180
    volumes:
      - ./work/locallnd/.lnd2:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    logging:
      driver: local
      options:
        max-size: "100m"



  lightning_node_3:
    image: awazcognitum/gig-gossip-base:0.1

    container_name: giggossip_lightning_node_3
    restart: on-failure
    # command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd
    command: /work/lnd/lnd-debug --lnddir=/work/locallnd/.lnd --wallet-unlock-password-file=/work/locallnd/.secret/password.txt
    ports:
      - 9736:9736
      - 11010:11010
      - 8181:8181
    volumes:
      - ./work/locallnd/.lnd3:/work/locallnd/.lnd:Z
      - ./work/locallnd/.secret:/work/locallnd/.secret:ro
    logging:
      driver: local
      options:
        max-size: "100m"



  nostr:
    image: python:3.9.17-slim-bookworm

    container_name: giggossip_nostr
    restart: on-failure
    working_dir: /work/locallnd/.nostr_relay
    command: sh -c "pip install nostr-relay && pip install SQLAlchemy==2.0.27 && nostr-relay -c config.yaml serve"
    ports:
      - 6969:6969
    volumes:
      - ./work/locallnd/.nostr_relay:/work/locallnd/.nostr_relay:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  # nostr2:
  #   image: python:3.10.13-alpine3.18

  #   container_name: giggossip_nostr2
  #   restart: on-failure
  #   working_dir: /work/locallnd/.nostr_relay
  #   command: sh -c "pip install nostr-relay && nostr-relay -c config.yaml serve"
  #   ports:
  #     - 6970:6970
  #   volumes:
  #     - ./work/locallnd/.nostr_relay2:/work/locallnd/.nostr_relay:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"


  # nostr3:
  #   image: python:3.10.13-alpine3.18

  #   container_name: giggossip_nostr3
  #   restart: on-failure
  #   working_dir: /work/locallnd/.nostr_relay
  #   command: sh -c "pip install nostr-relay && nostr-relay -c config.yaml serve"
  #   ports:
  #     - 6971:6971
  #   volumes:
  #     - ./work/locallnd/.nostr_relay3:/work/locallnd/.nostr_relay:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"




  # giggossip_api:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend_old.Dockerfile

  #   container_name: giggossip_api
  #   restart: on-failure
  #   # entrypoint: sh -c "dotnet ./NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net7.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip/"
  #   ports:
  #     - 7101:7101
  #     - 7189:7189
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   depends_on:
  #     - bitcoin
  #     - lightning_node_1
  #     - lightning_node_2
  #     - lightning_node_3


  logger_api:
    # image: giggossip_backend
    # build: 
    #   context: ../.
    #   dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile
    image: awazcognitum/giggossip-backend:latest

    container_name: logger_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigDebugLoggerAPI/bin/Debug/net8.0/GigDebugLoggerAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7187:7187
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  wallet_api:
    # image: giggossip_backend
    # build: 
    #   context: ../.
    #   dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile
    image: awazcognitum/giggossip-backend:latest

    container_name: wallet_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net8.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7101:7101
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  settler_api:
    # image: giggossip_backend
    # build: 
    #   context: ../.
    #   dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile
    image: awazcognitum/giggossip-backend:latest

    container_name: settler_api
    restart: on-failure
    entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigGossipSettlerAPI/bin/Debug/net8.0/GigGossipSettlerAPI.dll --basedir=/work/locallnd/.giggossip/"
    ports:
      - 7189:7189
    volumes:
      - ./work/locallnd/:/work/locallnd/:Z
    logging:
      driver: local
      options:
        max-size: "100m"


  # wallet_api2:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

  #   container_name: wallet_api2
  #   restart: on-failure
  #   entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net7.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip1/"
  #   ports:
  #     - 7102:7102
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"


  # settler_api2:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

  #   container_name: settler_api2
  #   restart: on-failure
  #   entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigGossipSettlerAPI/bin/Debug/net7.0/GigGossipSettlerAPI.dll --basedir=/work/locallnd/.giggossip1/"
  #   ports:
  #     - 7190:7190
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"


  # wallet_api3:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

  #   container_name: wallet_api3
  #   restart: on-failure
  #   entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigLNDWalletAPI/bin/Debug/net7.0/GigLNDWalletAPI.dll --basedir=/work/locallnd/.giggossip2/"
  #   ports:
  #     - 7103:7103
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"


  # settler_api3:
  #   image: giggossip_backend
  #   build: 
  #     context: ../.
  #     dockerfile: ./docker/docker_services_build/gigossip_backend.Dockerfile

  #   container_name: settler_api3
  #   restart: on-failure
  #   entrypoint: sh -c "dotnet ../gig-gossip-build/NGigGossip4Nostr/GigGossipSettlerAPI/bin/Debug/net7.0/GigGossipSettlerAPI.dll --basedir=/work/locallnd/.giggossip2/"
  #   ports:
  #     - 7191:7191
  #   volumes:
  #     - ./work/locallnd/:/work/locallnd/:Z
  #   logging:
  #     driver: local
  #     options:
  #       max-size: "100m"


networks:
  default:
    name: giggossip
    driver: bridge
