%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#FFFFFF',
      'primaryTextColor': '#000',
      'primaryBorderColor': '#000',
      'lineColor': '#000',
      'secondaryColor': '#000',
      'tertiaryColor': '#000'
    }
  }
}%%
sequenceDiagram
    activate Settler
    Settler->>Settler: Generates preimage
    Settler->>Settler: Computes payment hash for the preimage  
    Settler->>Issuer: Sends the preimage
    deactivate Settler
    activate Issuer
    Issuer->>Issuer: Creates a HODL invoice with the payment hash
    Issuer->>Payer: Sends the HODL invoice
    deactivate Issuer
    Payer->>Issuer: Pay (accepts the HODL invoice)
    Settler->>Payer: Reveals the preimage (settles the HODL invoice)
