%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'activationBorderColor':'#000',
      'activationBkgColor':'#F00',
      'primaryColor': '#FFF',
      'primaryTextColor': '#000',
      'primaryBorderColor': '#000',
      'lineColor': '#000',
      'secondaryColor': '#FFF',
      'labelBoxBorderColor':'#F00',
      'tertiaryColor': '#000',
      'fontFamily':'Times New Roman'
    }
  }
}%%
sequenceDiagram
    autonumber
    Originator->>Middleman: AskForBroadcastFrame
    activate Middleman
    Middleman-->>Originator: POWBroadcastConditionsFrame
    deactivate Middleman
    activate Originator
    Originator->>Middleman: POWBroadcastFrame
    deactivate Originator