%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#FFFFFF',
      'primaryTextColor': '#000',
      'primaryBorderColor': '#000',
      'lineColor': '#000',
      'secondaryColor': '#000',
      'tertiaryColor': '#000'
    }
  }
}%%
classDiagram
    class SignableObject{
        Bytes signature
        +sign(Bytes private_key)
        +verify(Bytes public_key):Boolean
    }
    class Invoice{
        +int amount
        +pay()
    }
    class HODLInvoice{
        +Bytes payment_hash
        +settle(Bytes preimage)
    }
    class ReplyPayload{
        +RequestPayload signed_request_payload
        +Bytes encrypted_reply_message
        +Bytes network_payment_hash
    }
    class ReplyFrame{
        +Certificate replier_certificate
        +OnionRoute forward_onion
    }
    SignableObject <|-- ReplyPayload
    Invoice <|-- HODLInvoice
    ReplyFrame  o--  ReplyPayload : signed_reply_payload
    ReplyPayload o-- Invoice: reply_invoice
    ReplyFrame o-- HODLInvoice: network_invoice
    
    