%%{
  init: {
    'theme': 'base',
    'themeVariables': {
      'primaryColor': '#FFFFFF',
      'primaryTextColor': '#000',
      'primaryBorderColor': '#000',
      'lineColor': '#000',
      'secondaryColor': '#000',
      'tertiaryColor': '#000',
      'fontFamily':'Times New Roman'
    }
  }
}%%
classDiagram
    class WorkRequest{
        +String pow_scheme
        +int pow_target
    }
    class POWBroadcastConditionsFrame{
        +UUID ask_id
        +DateTime valid_till
        +WorkRequest work_request
        +TimeDelta timestamp_tolerance
    }
    POWBroadcastConditionsFrame  o--  WorkRequest : work_request
    