name: Build Backend Docker Images 

on:
  push:
    branches: [ "main" ]


defaults:
  run:
    shell: pwsh

jobs:

  build-logger-api:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # build the container image and push it to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./net
          file: ./net/docker/backend/build_logger_api.Dockerfile
          push: true
          tags: awazcognitum/logger_api:latest


  build-wallet-api:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # build the container image and push it to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./net
          file: ./net/docker/backend/build_wallet_api.Dockerfile
          push: true
          tags: awazcognitum/wallet_api:latest


  build-settler-api:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # build the container image and push it to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./net
          file: ./net/docker/backend/build_settler_api.Dockerfile
          push: true
          tags: awazcognitum/settler_api:latest




  keypairgen:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3
      - # login to Docker Hub using the secrets provided
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - # build the container image and push it to Docker Hub
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./net
          file: ./net/docker/backend/build_keypairgen.Dockerfile
          push: true
          tags: awazcognitum/keypairgen:latest


  trigger-deploy-gohyper:
    runs-on: ubuntu-latest
    needs: [build-settler-api, build-wallet-api, build-logger-api]
    steps:
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '60' # for x seconds
      - name: Trigger deploy pipeline
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REGTEST_DEPLOY_TOKEN }}
          repository: ${{ secrets.REGTEST_DEPLOY_REPO }}
          event-type: deploy-giggossip-backend
          
