name: Build Docker Image Backend

on:
  push:
    branches: [ "main" ]

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NuGetDirectory: ${{ github.workspace }}/nuget
  RepoDirectory: ${{ github.workspace }}

defaults:
  run:
    shell: pwsh

jobs:
  build-nuget-packages:
    runs-on: ubuntu-latest
    steps:
      - # checkout to the repository on the build machine
        name: Checkout
        uses: actions/checkout@v3

      # Install the .NET SDK indicated in the global.json file
      - name: Setup .NET
        uses: actions/setup-dotnet@v4

      # Create the NuGet package in the folder from the environment variable NuGetDirectory
      - run: cd ${{ env.RepoDirectory }}/net/NGigGossip4Nostr/CryptoToolkit && dotnet pack --configuration Release --output ${{ env.NuGetDirectory }}

      - name: Publish NuGet package
        run: |
          foreach($file in (Get-ChildItem "${{ env.NuGetDirectory }}" -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_APIKEY }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }


